language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install --dev --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml tests

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
