language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0

before_script:
    - composer install --dev --no-interaction
    
script:
    - mkdir -p build/logs
    - phpunit --configuration phpunit.xml tests

after_script:
    - php vendor/bin/coveralls -v
