language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer install --dev --no-interaction
  - composer run-script check-code-style

script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml tests

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
